apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: skuad-ui-dev
  namespace: argocd
  annotations: 
    # notifications.argoproj.io/subscribe.on-sync-succeeded.slack: argocd
    notifications.argoproj.io/subscribe.on-sync-failed.slack: argocd
    notifications.argoproj.io/subscribe.on-sync-status-unknown.slack: argocd
    notifications.argoproj.io/subscribe.on-health-degraded.slack: argocd
    # notifications.argoproj.io/subscribe.on-deployed.slack: argocd
spec:
  destination:
    namespace: dev
    server: 'https://kubernetes.default.svc'
  source:
    path: skuad-ui
    repoURL: 'https://gitlab.skuad.in/sre/helm-charts.git'
    targetRevision: HEAD
    helm:
      releaseName: skuad-ui
      valueFiles:
        - values.dev.yaml
  project: dev
  revisionHistoryLimit: 2
  syncPolicy:
    automated: {}
