replicaCount: 1
revisionHistoryLimit: 2
image:
  repository: asia-docker.pkg.dev/skuad-core-dev/gke/acl
  pullPolicy: IfNotPresent
  tag: dev-fdc7a89a
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
secretsFrom: acl
# Any Extra environment variables.
extraEnv:
  NODE_OPTIONS: --max_old_space_size=4096
  NODE_ENV: development
serviceAccount:
  create: false
  annotations: {}
  name: ""
podAnnotations: {}
podSecurityContext: {}
# fsGroup: 2000

securityContext:
  allowPrivilegeEscalation: false
  runAsUser: 0
  readOnlyRootFilesystem: false
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000
service:
  type: ClusterIP
  port: 3002
ingress:
  enabled: false
  className: ""
  annotations:
    kubernetes.io/ingress.global-static-ip-name: ui-storybook-dev
    networking.gke.io/managed-certificates: skuad-ui
    networking.gke.io/v1beta1.FrontendConfig: skuad-ui
  domains:
    - acl-dev.skuad.in
  tls: []
resources:
  limits:
    cpu: 1000m
    memory: 2048Mi
  requests:
    cpu: 200m
    memory: 512Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 6
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 60
nodeSelector: {}
tolerations: []
affinity: {}
istio:
  internal:
    gateway: internal-ingress-gateway
    domain: dev.internal.skuad.in
  external:
    gateway: istio-ingress/istio-external-ingress
    hosts:
      - acl-dev.skuad.io
    http:
      - match:
          - uri:
              prefix: /
        route:
          - destination:
              port:
                number: 3002
              host: acl.dev.svc.cluster.local
