apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ include "app.fullname" . }}
spec:
  healthCheck:
    checkIntervalSec: 30
    port: {{ .Values.service.port }}
    type: HTTP
    requestPath: /api/v1/get-healthy-check