{{- if .Values.ingress.enabled -}}
apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: {{ include "app.fullname" . }}
spec:
  domains: 
  {{ toYaml .Values.ingress.domains | indent 2 }}
{{- end }}  
