apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "app.fullname" . }}-internal
spec:
  gateways:
    - {{ .Values.istio.internal.gateway }}
  hosts:
    - {{ include "app.fullname" . }}.{{ .Values.istio.internal.domain }}
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            port:
              number: {{ .Values.service.port }}
            host: {{ include "app.fullname" . }}
